CONST_ENV_CONFIG = "env_config"
CONST_ENV_TYPE = "env_type"

CONST_BRAX = "brax"
CONST_DM_CONTROL = "dm_control"
CONST_GYM = "gym"

VALID_ENV_TYPE = [CONST_DM_CONTROL, CONST_GYM, CONST_BRAX]


CONST_BASIS_POLYNOMIAL = "polynomial"

VALID_BASIS_FUNCTION = [CONST_BASIS_POLYNOMIAL]

# MNIST
CONST_MULTITASK_MNIST_FINEGRAIN = "multitask_mnist_finegrain"
CONST_STRATIFIED_MULTITASK_MNIST_FINEGRAIN = "stratified_multitask_mnist_finegrain"
CONST_MULTITASK_MNIST_RANDOM_BINARY = "multitask_mnist_random_binary"
CONST_MULTITASK_MNIST_BURSTY = "multitask_mnist_bursty"
VALID_MNIST_TASKS = [
    CONST_MULTITASK_MNIST_FINEGRAIN,
    CONST_STRATIFIED_MULTITASK_MNIST_FINEGRAIN,
    CONST_MULTITASK_MNIST_RANDOM_BINARY,
    CONST_MULTITASK_MNIST_BURSTY,
]

# Omniglot
CONST_MULTITASK_OMNIGLOT_FINEGRAIN = "multitask_omniglot_finegrain"
CONST_MULTITASK_OMNIGLOT_BURSTY = "multitask_omniglot_bursty"
CONST_MULTITASK_OMNIGLOT_N_SHOT_K_WAY = "multitask_omniglot_n_shot_k_way"
CONST_MULTITASK_OMNIGLOT_BURSTY_TF = "multitask_omniglot_bursty_tf"
CONST_MULTITASK_OMNIGLOT_N_SHOT_K_WAY_TF = "multitask_omniglot_n_shot_k_way_tf"
VALID_OMNIGLOT_TASKS = [
    CONST_MULTITASK_OMNIGLOT_BURSTY,
    CONST_MULTITASK_OMNIGLOT_FINEGRAIN,
    CONST_MULTITASK_OMNIGLOT_N_SHOT_K_WAY,
    CONST_MULTITASK_OMNIGLOT_BURSTY_TF,
    CONST_MULTITASK_OMNIGLOT_N_SHOT_K_WAY_TF,
]

# Dataset
CONST_MULTITASK_TOY_REGRESSION = "multitask_toy_regression"
CONST_MULTITASK_ND_LINEAR_REGRESSION = "multitask_nd_linear_regression"
CONST_MULTITASK_ND_LINEAR_CLASSIFICATION = "multitask_nd_linear_classification"
CONST_MULTITASK_ND_RANDOM_CLASSIFICATION = "multitask_nd_random_classification"
CONST_MNIST = "mnist"
CONST_ONE_HOT_CLASSIFICATION = "one_hot_classification"
CONST_OMNIGLOT = "omniglot"
CONST_OMNIGLOT_TF = "omniglot_tf"
CONST_TIGHT_FRAME = "tight_frame"

VALID_DATASET = [
    CONST_MULTITASK_TOY_REGRESSION,
    CONST_MULTITASK_ND_LINEAR_REGRESSION,
    CONST_MULTITASK_ND_LINEAR_CLASSIFICATION,
    CONST_MULTITASK_ND_RANDOM_CLASSIFICATION,
    CONST_MNIST,
    CONST_ONE_HOT_CLASSIFICATION,
    CONST_OMNIGLOT,
    CONST_OMNIGLOT_TF,
    CONST_TIGHT_FRAME,
]
