CONST_ENV_CONFIG = "env_config"
CONST_ENV_TYPE = "env_type"

CONST_DM_CONTROL = "dm_control"
CONST_GYM = "gym"

VALID_ENV_TYPE = [CONST_DM_CONTROL, CONST_GYM]


CONST_BASIS_POLYNOMIAL = "polynomial"

VALID_BASIS_FUNCTION = [CONST_BASIS_POLYNOMIAL]


CONST_MULTITASK_TOY_REGRESSION = "multitask_toy_regression"
CONST_MULTITASK_ND_LINEAR_REGRESSION = "multitask_nd_linear_regression"
CONST_MULTITASK_ND_LINEAR_CLASSIFICATION = "multitask_nd_linear_classification"
VALID_DATASET = [
    CONST_MULTITASK_TOY_REGRESSION,
    CONST_MULTITASK_ND_LINEAR_REGRESSION,
    CONST_MULTITASK_ND_LINEAR_CLASSIFICATION,
]
