CONST_ENV_CONFIG = "env_config"
CONST_ENV_TYPE = "env_type"

CONST_DM_CONTROL = "dm_control"
CONST_GYM = "gym"

VALID_ENV_TYPE = [CONST_DM_CONTROL, CONST_GYM]


CONST_BASIS_POLYNOMIAL = "polynomial"

VALID_BASIS_FUNCTION = [CONST_BASIS_POLYNOMIAL]
