CONST_CATEGORICAL = "categorical"
CONST_GAUSSIAN = "gaussian"
CONST_HINGE = "hinge"
CONST_L2 = "l2"
CONST_SIGMOID_BCE = "sigmoid_bce"

VALID_LOSS = [CONST_CATEGORICAL, CONST_GAUSSIAN, CONST_L2, CONST_HINGE, CONST_SIGMOID_BCE]

CONST_AUX = "aux"
CONST_AGG_LOSS = "aggregate_loss"
CONST_COEFFICIENT = "coefficient"
CONST_MEAN = "mean"
CONST_METRIC = "metric"
CONST_LOSS = "loss"
CONST_PREDICTIONS = "predictions"
CONST_SUM = "sum"

VALID_REDUCTION = [CONST_SUM, CONST_MEAN]
