CONST_MLP = "mlp"

VALID_ARCHITECTURE = [CONST_MLP]


CONST_DETERMINISTIC = "deterministic"
CONST_GAUSSIAN = "gaussian"
CONST_SQUASHED_GAUSSIAN = "squashed_gaussian"
VALID_POLICY_DISTRIBUTION = [
    CONST_DETERMINISTIC,
    CONST_GAUSSIAN,
    CONST_SQUASHED_GAUSSIAN,
]

CONST_MODEL = "model"
CONST_POLICY = "policy"
CONST_REPRESENTATION = "representation"
CONST_VF = "vf"

CONST_MIN_STD = "min_std"

DEFAULT_MIN_STD = 1e-7
