CONST_CNN = "cnn"
CONST_ENCODER_PREDICTOR = "encoder_predictor"
CONST_ENSEMBLE = "ensemble"
CONST_ICL_GPT = "icl_gpt"
CONST_GPT = "gpt"
CONST_MLP = "mlp"

VALID_ARCHITECTURE = [
    CONST_CNN,
    CONST_ENCODER_PREDICTOR,
    CONST_ENSEMBLE,
    CONST_ICL_GPT,
    CONST_MLP,
]

VALID_TOKENIZER_TYPE = [
    CONST_CNN,
    CONST_MLP,
]

CONST_BANG_BANG = "bang_bang"
CONST_DETERMINISTIC = "deterministic"
CONST_GAUSSIAN = "gaussian"
CONST_SOFTMAX = "softmax"
CONST_SQUASHED_GAUSSIAN = "squashed_gaussian"
VALID_POLICY_DISTRIBUTION = [
    CONST_BANG_BANG,
    CONST_DETERMINISTIC,
    CONST_GAUSSIAN,
    CONST_SOFTMAX,
    CONST_SQUASHED_GAUSSIAN,
]

CONST_ENCODER = "encoder"
CONST_MODEL = "model"
CONST_POLICY = "policy"
CONST_PREDICTOR = "predictor"
CONST_REPRESENTATION = "representation"
CONST_VF = "vf"

CONST_STD_TRANSFORM = "std_transform"

CONST_MIN_STD = "min_std"
CONST_TEMPERATURE = "temperature"

DEFAULT_MIN_STD = 1e-7
DEFAULT_TEMPERATURE = 1.0

CONST_IDENTITY = "identity"
CONST_RELU = "relu"
CONST_TANH = "tanh"
VALID_ACTIVATION = [CONST_IDENTITY, CONST_RELU, CONST_TANH]

CONST_INPUT_TOKENIZER = "input_tokenizer"
CONST_OUTPUT_TOKENIZER = "output_tokenizer"

CONST_POSITIONAL_ENCODING = "positional_encoding"
CONST_NO_ENCODING = "no_encoding"
CONST_DEFAULT_ENCODING = "default"
VALID_POSITIONAL_ENCODING = [CONST_NO_ENCODING, CONST_DEFAULT_ENCODING]
