CONST_MLP = "mlp"

VALID_ARCHITECTURE = [CONST_MLP]


CONST_GAUSSIAN = "gaussian"
CONST_SQUASHED_GAUSSIAN = "squashed_gaussian"
VALID_POLICY_DISTRIBUTION = [CONST_GAUSSIAN, CONST_SQUASHED_GAUSSIAN]

CONST_MODEL = "model"
CONST_POLICY = "policy"
CONST_VF = "vf"
